# Generated by Django 6.0.6 on 2026-06-17 10:32

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True, verbose_name='Data urodzenia'),
        ),
        migrations.AddField(
            model_name='user',
            name='dietetitian',
            field=models.ForeignKey(blank=True, help_text='Wybierz dietetyka z listy, jeśli użytkownik jest pacjentem.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='patients', to=settings.AUTH_USER_MODEL, verbose_name='Dietetyk prowadzący'),
        ),
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'Mężczyzna'), ('F', 'Kobieta')], max_length=1, null=True, verbose_name='Płeć'),
        ),
        migrations.AddField(
            model_name='user',
            name='height_cm',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(50)], verbose_name='Wzrost (cm)'),
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('DIETETITAN', 'Dietetyk'), ('PATIENT', 'Pacjent'), ('STANDARD', 'Użytkownik standardowy')], default='STANDARD', max_length=20, verbose_name='Rola'),
        ),
        migrations.AddField(
            model_name='user',
            name='weight_kg',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(10.0)], verbose_name='Waga (kg)'),
        ),
    ]
