# Generated by Django 6.0.6 on 2026-06-18 21:25

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_date_of_birth_user_dietetitian_user_gender_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='dietetitian',
        ),
        migrations.AddField(
            model_name='user',
            name='dietitian',
            field=models.ForeignKey(blank=True, help_text='Select a dietitian from the list if the user is a patient.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='patients', to=settings.AUTH_USER_MODEL, verbose_name='Leading dietitian'),
        ),
        migrations.AlterField(
            model_name='user',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True, verbose_name='Date of birth'),
        ),
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female')], max_length=1, null=True, verbose_name='Gender'),
        ),
        migrations.AlterField(
            model_name='user',
            name='height_cm',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(10)], verbose_name='Height (cm)'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('DIETITAN', 'Dietitian'), ('PATIENT', 'Patient'), ('STANDARD', 'Standard User')], default='STANDARD', max_length=20, verbose_name='Role'),
        ),
        migrations.AlterField(
            model_name='user',
            name='weight_kg',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(2.0)], verbose_name='Weight (kg)'),
        ),
    ]
