# Generated by Django 6.0.6 on 2026-06-18 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_dietitianrequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('DIETITIAN', 'Dietitian'), ('PATIENT', 'Patient'), ('STANDARD', 'Standard User')], default='STANDARD', max_length=20, verbose_name='Role'),
        ),
    ]
