# Generated by Django 6.0.6 on 2026-06-19 13:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diets', '0002_alter_dietplan_patient'),
        ('products', '0002_alter_product_calories_per_100g_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MealLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(help_text='Date')),
                ('meal_type', models.CharField(choices=[('BREAKFAST', 'Śniadanie'), ('LUNCH', 'II Śniadanie'), ('DINNER', 'Obiad'), ('SNACK', 'Podwieczorek'), ('SUPPER', 'Kolacja')], max_length=20)),
                ('weight_in_grams', models.PositiveIntegerField(blank=True, null=True)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.product')),
                ('recipe', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='diets.recipe')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meal_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['date', 'meal_type'],
            },
        ),
    ]
