# Generated by Django 6.0.6 on 2026-06-09 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('calories_per_100g', models.PositiveIntegerField()),
                ('protein_per_100g', models.PositiveIntegerField()),
                ('fat_per_100g', models.PositiveIntegerField()),
                ('carbs_per_100g', models.PositiveIntegerField()),
            ],
        ),
    ]
